"""test

Revision ID: 05ee19a6fef8
Revises: 5d40d2e21219
Create Date: 2023-03-28 10:08:47.440294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ee19a6fef8'
down_revision = '5d40d2e21219'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
