"""added something for restaurant

Revision ID: 8c27b5be80ce
Revises: d5f13206da6e
Create Date: 2023-03-24 17:59:16.489154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c27b5be80ce'
down_revision = 'd5f13206da6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('location', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('cuisine', sa.String(), nullable=True))
    op.drop_column('restaurants', 'delivered_at')
    op.drop_column('restaurants', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('restaurants', sa.Column('delivered_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('restaurants', 'cuisine')
    op.drop_column('restaurants', 'location')
    # ### end Alembic commands ###
