"""Done? done?

Revision ID: fcdebda57765
Revises: 5d40d2e21219
Create Date: 2023-03-24 14:03:24.225014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdebda57765'
down_revision = '5d40d2e21219'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
